In [ ]:
# Computational Graph

In [5]:
import tensorflow as tf

# 2.x 버전에서는 Session이 따로 필요하지 않다.
# 직관적으로 변함.

node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)

print("node1:", node1, "node2:", node2)
print("node3: ", node3)


node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3:  tf.Tensor(7.0, shape=(), dtype=float32)


In [6]:
print("node1: ", node1.numpy(), "node2:", node2.numpy())
print("node3: ", node3.numpy())

node1:  3.0 node2: 4.0
node3:  7.0


In [ ]:
# Placeholder

In [13]:
# TensorFlow 2.x 버전에서는 placeholder를 사용하지 않음
# a = tf.placeholder(tf.float32)
# b = tf.placeholder(tf.float32)
# adder_node = a + b

# 대신 @tf.function을 사용한다.

@tf.function
def adder_node(a, b):
    return a + b

print(adder_node(3, 4.5))
print(adder_node(3, 4.5).numpy())

# 예제와는 다르게 행렬을 요소를 더하지 않고 행렬을 append 해버린다.
print(adder_node([1,3], [2,4]))

tf.Tensor(7.5, shape=(), dtype=float32)
7.5
[<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=4>]
<class 'list'>
