In [ ]:
# 1.

In [12]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

i = np.array([0.9, 0.1, 0.8], float).reshape(3,1)
w_input_hidden = np.array([0.9, 0.3, 0.4, 0.2, 0.8, 0.2, 0.1, 0.5, 0.6]).reshape(3,3)
w_hidden_output = np.array([.3, .7, .5, .6, .5, .2, .8, .1, .9]).reshape(3,3)

i
w_input_hidden
w_hidden_output

array([[0.9],
       [0.1],
       [0.8]])

array([[0.9, 0.3, 0.4],
       [0.2, 0.8, 0.2],
       [0.1, 0.5, 0.6]])

array([[0.3, 0.7, 0.5],
       [0.6, 0.5, 0.2],
       [0.8, 0.1, 0.9]])

In [11]:
x_hidden = np.dot(w_input_hidden, i)
x_hidden

o_hidden = sigmoid(x_hidden)
o_hidden

array([[1.16],
       [0.42],
       [0.62]])

array([[0.76133271],
       [0.60348325],
       [0.65021855]])

In [15]:
x_output = np.dot(w_hidden_output, o_hidden)
x_output

o_output = sigmoid(x_output)
o_output

array([[0.97594736],
       [0.88858496],
       [1.25461119]])

array([[0.72630335],
       [0.70859807],
       [0.77809706]])

In [ ]:
# 2.

In [21]:
e_output1 = 0.8
e_output2 = 0.5
w11 = 2.0
w12 = 1.0
w21 = 3.0
w22 = 4.0

e_hidden1 = e_output1 * w11 / (w11 + w21) + e_output2 * w12 / (w12 + w22) 
e_hidden2 = e_output2 * w22 / (w12 + w22) + e_output1 * w21/ (w11 + w21)
e_hidden1
e_hidden2

0.42000000000000004

0.8800000000000001

In [22]:
w11 = 3.0
w12 = 1.0
w21 = 2.0
w22 = 7.0

e_input1 = e_hidden1 * w11 / (w11 + w21) + e_hidden2 * w12 / (w12 + w22) 
e_input2 = e_hidden2 * w22 / (w12 + w22) + e_hidden1 * w21/ (w11 + w21)
e_input1
e_input2

0.3620000000000001

0.9380000000000002

In [ ]:
# 3.

In [38]:
e_output1 = 0.8
e_output2 = 0.5
w11 = 2.0
w12 = 1.0
w21 = 3.0
w22 = 4.0

o1 = 0.4
o2 = 0.5

w11_update = -e_output1 * sigmoid(w11 * o1 + w21 * o2) * (1-sigmoid(w11 * o1 + w21 * o2)) * o1
w12_update = -e_output2 * sigmoid(w12 * o1 + w22 * o2) * (1-sigmoid(w12 * o1 + w22 * o2)) * o2
w21_update = -e_output1 * sigmoid(w11 * o1 + w21 * o2) * (1-sigmoid(w11 * o1 + w21 * o2)) * o1
w22_update = -e_output2 * sigmoid(w12 * o1 + w22 * o2) * (1-sigmoid(w12 * o1 + w22 * o2)) * o2

w11 - w11_update
w12 - w12_update
w21 - w21_update
w22 - w22_update

2.026502261437037

1.019063749762963

3.026502261437037

4.019063749762963

In [42]:
w = np.array([2.0, 3.0, 1.0, 4.0]).reshape(2,2)
oj = np.array([.4, .5]).reshape(2,1)

s = np.dot(w, oj)

e = np.array([e_output1, e_output2])

array([[2.3],
       [2.4]])

In [ ]:
# 4.