In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy
numpy.__version__

'1.20.3'

In [4]:
L =list(range(10))

L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
type(L2[0])

L3 = [True, '2', 3.0, 4]

[type(item) for item in L3]

str

[bool, str, float, int]

In [6]:
import array

L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
import numpy as np

np.array([1, 4, 2, 5, 3])
np.array([3.14, 4, 2, 3])
np.array([1, 2, 3, 4], dtype="float32")

np.array([range(i, i+3) for i in [2, 4, 6]])

array([1, 4, 2, 5, 3])

array([3.14, 4.  , 2.  , 3.  ])

array([1., 2., 3., 4.], dtype=float32)

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
import numpy as np

# 0으로 채운 길이 10의 정수 배열
np.zeros(10, dtype=int)

# 1로 채운 3x5 부동 소수점 배열
np.ones((3, 5), dtype=float)

# 3.14로 채운 3x5 배열
np.full((3, 5), 3.14)

np.arange(0, 20, 2)

np.linspace(0, 1, 5)

# 0과 1사이의 난수
np.random.random((3, 3))

# 정규 분포(평균=0, 표준 편차=1)의 난수로 채운 3x3 배열 만들기
np.random.normal(0, 1, (3, 3))

# [0, 10] 사이의 정수 난수
np.random.randint(0, 10, (3, 3))

# 3x3 단위행렬(곱했을 때 1과 같은 역할을 하는 행렬)
np.eye(3)

np.empty(3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

array([[0.98427509, 0.39355296, 0.15386372],
       [0.1838299 , 0.99767569, 0.44354461],
       [0.08018922, 0.78886888, 0.45735895]])

array([[-1.15457893, -0.88206445,  1.74954067],
       [-0.59633505,  0.32125915,  0.23043316],
       [ 0.85921131, -1.03314603, -0.40758533]])

array([[9, 3, 2],
       [1, 1, 8],
       [6, 6, 2]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([1., 1., 1.])

In [16]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

print("dtype: ", x3.dtype)

print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

x1

x1[0]

x1[4]

x1[-1]

x1[-2]

x2

x2[0, 0]

x2[2, 0]

x2[2, -1]

x2[0, 0] = 12
x2

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int32
itemsize:  4 bytes
nbytes:  240 bytes


array([5, 0, 3, 3, 7, 9])

5

7

9

7

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

3

1

7

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [13]:
x = np.arange(10)
x

x[:5]
x[5:]
x[4:7]
x[::2]
x[1::2]
x[::-1]
x[5::2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4])

array([5, 6, 7, 8, 9])

array([4, 5, 6])

array([0, 2, 4, 6, 8])

array([1, 3, 5, 7, 9])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array([5, 7, 9])

In [25]:
x2 = np.random.randint(10, size=(3, 4))
x2

x2[:2, :3]

x2[:3, ::2]

x2[::-1, ::-1]

print(x2[:, 0])

print(x2[0, :])

print(x2[0])

x2_sub = x2[:2, :2]
print(x2_sub)

x2_sub[0, 0] = 99
print(x2_sub)

array([[6, 2, 4, 1],
       [4, 0, 4, 2],
       [5, 0, 0, 4]])

array([[6, 2, 4],
       [4, 0, 4]])

array([[6, 4],
       [4, 4],
       [5, 0]])

array([[4, 0, 0, 5],
       [2, 4, 0, 4],
       [1, 4, 2, 6]])

[6 4 5]
[6 2 4 1]
[6 2 4 1]
[[6 2]
 [4 0]]
[[99  2]
 [ 4  0]]


In [32]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

x= np.array([1,2,3])

x.reshape((1, 3))

x[np.newaxis, :]

x.reshape((3, 1))

x[:, np.newaxis]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3]])

array([[1, 2, 3]])

array([[1],
       [2],
       [3]])

array([[1],
       [2],
       [3]])

In [40]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

z = [99, 99, 99]
print(np.concatenate([x, y, z]))

grid = np.array([[1,2,3], [4,5,6]])

# 첫 번째 축을 따라 연결
np.concatenate([grid, grid])

# 두 번째 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid, grid], axis=1)

x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])

np.vstack([x, grid])

y = np.array([[99], [99]])
np.hstack([grid, y])

array([1, 2, 3, 3, 2, 1])

[ 1  2  3  3  2  1 99 99 99]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [8]:
import numpy as np

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))
grid

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
print()

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[1 2 3] [99 99] [3 2 1]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [10]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)
np.absolute(x)
np.abs(x)

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

theta = np.linspace(0, np.pi, 3)
print("theta =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

array([2, 1, 0, 1, 2])

array([2, 1, 0, 1, 2])

array([2, 1, 0, 1, 2])

array([5., 5., 2., 1.])

theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [11]:
x = [-1, 0, 1]
print("x =", x)
print("arcsin(x)", np.arcsin(x))
print("arccos(x)", np.arccos(x))
print("arctan(x)", np.arctan(x))

x = [-1, 0, 1]
arcsin(x) [-1.57079633  0.          1.57079633]
arccos(x) [3.14159265 1.57079633 0.        ]
arctan(x) [-0.78539816  0.          0.78539816]


In [12]:
x = [1,2,3]
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [14]:
x = [1,2,4,10]
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [15]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1+x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1+x) = [0.         0.0009995  0.00995033 0.09531018]
